### ISSUE TITLE
Meerdere Package.json files?

### ISSUE THREAD

**Issue by Erveon** [simodecl/hearth#1]
Waarom zijn er meerdere?

Er kan ook met 1 package.json gewerkt worden (1 project).
Dat is makkelijker voor development en CI/CD.

Om aan Vue te zeggen dat het in de `/client` folder moet kijken ipv root kan je dit configureren in de vue.config.js file (Deze bestaat nog niet in dit project). Je maakt die dus gewoon aan in de root folder.

De contents hiervan zouden zijn:
```javascript
module.exports = {
    configureWebpack: {
        resolve: {
            alias: {
                '@': __dirname + '/client/src'
            }
        },
        entry: {
            app: './client/src/main.js'
        }
    },
}
```

Er is ook [documentatie](https://cli.vuejs.org/config/) van de Vue config.
Zeker waard om eens te bekijken voor bvb global css en proxy server voor met de back-end te linken tijdens development.

**Comment by simodecl** [comment]
#97757c0 Ik heb het aangepast.
