### ISSUE TITLE
URL Encoding

### ISSUE THREAD

**Issue by Erveon** [simodecl/hearth#6]
Momenteel zie ik dingen zoals

```javascript
url: 'https://api.spotify.com/v1/search?q=' + req.query.q.replace(' ', '%20') + '&type=track&limit=10',
```

Dit kan op een betere, ingebouwde manier:

```javascript
encodeURIComponent(input)
````

Op deze manier heb je zeker alle special character use-cases afgedekt ipv enkel spatie.

**Comment by simodecl** [comment]
Bedankt voor de tip!
